name: Deploy App

on:
  push:
    branches: [ 'dev' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_DEMO_HOST }}
          username: ${{ secrets.DEV_DEMO_USER }}
          password: ${{ secrets.DEV_DEMO_PASS }}
          script: |
            cd /var/www/Sonovy

            # Git değişikliklerini al
            git pull origin dev

            # Önce izinleri ayarla
            find . -type f -exec chmod 664 {} \;
            find . -type d -exec chmod 775 {} \;
            chmod -R ug+rwx vendor storage bootstrap/cache node_modules

            # Cache ve vendor temizliği
            rm -rf vendor node_modules
            rm -rf storage/framework/cache/*
            mkdir -p storage/framework/cache/laravel-excel
            mkdir vendor

            # İzinleri ayarla
            chown -R $USER:$USER .
            chmod -R 775 .

            # Composer bağımlılıklarını yükle
            php -d memory_limit=512M /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist

            # Frontend assets'leri derle
            mkdir -p node_modules
            chown -R $USER:$USER node_modules
            chmod -R 775 node_modules
            npm install
            npm run build

            # Laravel komutlarını çalıştır
            php artisan migrate --force
            php artisan tenants:migrate --force
            php artisan storage:link || true
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up

            # Supervisor'ı yeniden başlat
            systemctl restart supervisor || true

            # Dizin yapısını oluştur ve izinleri ayarla
            mkdir -p storage/framework/{sessions,views,cache,testing}
            mkdir -p storage/framework/cache/laravel-excel
            chown -R www-data:www-data .
            find . -type f -exec chmod 664 {} \;
            find . -type d -exec chmod 775 {} \;
            chmod -R ug+rwx storage bootstrap/cache
