name: Deploy App

on:
  push:
    branches: [ 'dev' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_DEMO_HOST }}
          username: ${{ secrets.DEV_DEMO_USER }}
          password: ${{ secrets.DEV_DEMO_PASS }}
          script: |
            cd /var/www/Sonovy

            # Git değişikliklerini al
            git pull origin dev

            # Önce izinleri ayarla
            rm -rf vendor
            mkdir vendor
            chown -R $USER:$USER .
            chmod -R 775 .

            # Composer bağımlılıklarını yükle
            php -d memory_limit=512M /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist

            # Frontend assets'leri derle
            npm install
            npm run build

            # Laravel komutlarını çalıştır
            php artisan migrate --force
            php artisan tenants:migrate --force
            php artisan storage:link || true
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up

            # Supervisor'ı yeniden başlat
            systemctl restart supervisor || true

            # En son olarak dosya sahipliğini ve izinleri ayarla
            chown -R www-data:www-data .
            chmod -R 775 storage bootstrap/cache public app
