name: Deploy App

on:
  push:
    branches: [ 'dev' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_DEMO_HOST }}
          username: ${{ secrets.DEV_DEMO_USER }}
          password: ${{ secrets.DEV_DEMO_PASS }}
          script: |
            cd /var/www/Sonovy

            # Git değişikliklerini al
            sudo git pull origin dev

            # Composer bağımlılıklarını yükle
            sudo php -d memory_limit=512M /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist

            # Frontend assets'leri derle
            sudo npm install
            sudo npm run build

            # Laravel komutlarını çalıştır
            sudo php artisan migrate --force
            sudo php artisan tenants:migrate --force
            sudo php artisan storage:link || true
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan up

            # Supervisor'ı yeniden başlat
            sudo systemctl restart supervisor

            # En son olarak dosya sahipliğini ve izinleri ayarla
            sudo chown -R www-data:www-data /var/www/Sonovy
            sudo chmod -R 775 /var/www/Sonovy/storage /var/www/Sonovy/bootstrap/cache /var/www/Sonovy/public /var/www/Sonovy/app
