name: Deploy App

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  laravel-prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env from secrets
        run: echo "${{ secrets.DEV_DEMO_ENV }}" | base64 --decode > .env

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, ctype, pdo, curl, json, xml, fileinfo, pdo_pgsql, pdo_mysql, tokenizer, session, bcmath, gd, exif, iconv, intl, openssl, pgsql, simplexml

      - name: Install Composer Dependencies
        run: php -d memory_limit=2048M /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist --no-scripts

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Compile Frontend Assets
        run: npm install && npm run build

      - name: Create Deployment Archive
        run: |
          tar -czf deploy.tar.gz --exclude=*.git --exclude=deploy.tar.gz --exclude=node_modules --exclude=.env --exclude=storage/logs --exclude=storage/framework *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.tar.gz

  laravel-deploy:
    runs-on: ubuntu-latest
    needs: laravel-prepare

    steps:
      - name: Download Deployment Archive
        uses: actions/download-artifact@v4
        with:
          name: deploy

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_DEMO_HOST }}
          username: ${{ secrets.DEV_DEMO_USER }}
          password: ${{ secrets.DEV_DEMO_PASS }}
          source: deploy.tar.gz
          target: /var/www/Sonovy/
          port: 22
          tar_enable: false  # Tar işlemini devre dışı bırakıyoruz

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5  # Mevcut bir sürüm kullanıyoruz
        with:
          host: ${{ secrets.DEV_DEMO_HOST }}
          username: ${{ secrets.DEV_DEMO_USER }}
          password: ${{ secrets.DEV_DEMO_PASS }}
          script: |
            cd /var/www/Sonovy
            # Eski public dosyalarını sil
            sudo rm -rf public/assets/build public/assets public/robots.txt public/index.php public/.htaccess
            sudo rm -rf public/assets/countries.json public/assets/cities.json public/assets/states.json public/assets/timezones.json

            # Yeni dosyaları çıkar ve var olanların üzerine yaz
            sudo tar --overwrite -xzf deploy.tar.gz

            # Deploy dosyasını kaldır
            sudo rm -rf deploy.tar.gz

            # Dosya ve dizin izinlerini ayarla
            sudo chown -R www-data:www-data /var/www/Sonovy
            sudo chmod -R 775 /var/www/Sonovy/storage /var/www/Sonovy/bootstrap/cache /var/www/Sonovy/public /var/www/Sonovy/app

            # Composer bağımlılıklarını yükle
            cd /var/www/Sonovy
            sudo php -d memory_limit=512M /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist

            # Laravel komutlarını çalıştır
            sudo php artisan migrate --force
            sudo php artisan tenants:migrate --force
            sudo php artisan tenants:seed --class="Database\\Seeders\\AdminSeeder"
            sudo php artisan tenants:seed --class="Database\\Seeders\\SettingSeeder"
            sudo php artisan storage:link || true
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan up

            # Node.js bağımlılıklarını yükle
            sudo npm install

            # Supervisor ve Laravel Echo Server kurulumu
            sudo apt-get update
            sudo apt-get install -y supervisor npm
            sudo npm install -g laravel-echo-server

            # Supervisor'ı yeniden başlat
            sudo systemctl restart supervisor